with open('assets/css/style.css', 'a', encoding='utf-8') as f:
    f.write('\n\n/* ========================================================================= */\n')
    f.write('/* AGGRESSIVE OVERRIDES - TO BE REFACTORED LATER                           */\n')
    f.write('/* ========================================================================= */\n\n')
    
    f.write('/* 1. Force white bullets on About page */\n')
    f.write('body[data-page="about"] .about-me .content ul li i, \n')
    f.write('.about-me .content ul li i.icofont-rounded-right {\n')
    f.write('  color: #ffffff !important;\n')
    f.write('  font-weight: 800 !important;\n')
    f.write('  font-size: 20px !important;\n')
    f.write('  opacity: 1 !important;\n')
    f.write('}\n\n')
    
    f.write('/* 2. Fix header overlap globally */\n')
    f.write('section.section-show {\n')
    f.write('  top: 160px !important;\n')
    f.write('}\n')
    f.write('@media (max-width: 992px) {\n')
    f.write('  section.section-show { top: 120px !important; }\n')
    f.write('}\n')
    f.write('@media (max-width: 768px) {\n')
    f.write('  section.section-show { top: 90px !important; }\n')
    f.write('}\n\n')
    
    f.write('/* 3. Center social links on contacts page */\n')
    f.write('body[data-page="contacts"] .contact .info-box .social-links {\n')
    f.write('  margin: 14px auto 0 !important;\n')
    f.write('  display: flex !important;\n')
    f.write('  justify-content: center !important;\n')
    f.write('  align-items: center !important;\n')
    f.write('  gap: 15px !important;\n')
    f.write('}\n\n')
    
    f.write('/* 4. Fix project filters centering */\n')
    f.write('#projects-filters {\n')
    f.write('  display: flex !important;\n')
    f.write('  justify-content: center !important;\n')
    f.write('  margin: 0 auto 32px !important;\n')
    f.write('  width: fit-content !important;\n')
    f.write('}\n')
